version: '3.9'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: 'always'
    container_name: members-form
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: members-form
      MYSQL_PASSWORD: root

volumes:
  db_data: {}
